import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";

import "./globals.css";
import QueryProvider from "./lib/query_provider";

const font = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "etudier",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
